# version: '3.8'

services:
  db:
    container_name: "instant_chat_db"
    image: "postgres:12.4-alpine"
    volumes:
      - "./database/postgres-data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    restart: "unless-stopped"